import * as FileSystem from 'expo-file-system/legacy';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { getDB } from '../database';

export const ReportUtils = {
  /**
   * Generates a CSV from a data array and shares it.
   */
  async downloadCSV(title: string, data: any[]) {
    if (data.length === 0) return alert('No data to export');

    const headers = Object.keys(data[0]);
    const csvRows = [
      headers.join(','), // Header row
      ...data.map(row =>
        headers.map(fieldName => {
          const value = row[fieldName] ?? '';
          // Simple CSV escaping: wrap in quotes and escape internal quotes
          return `"${String(value).replace(/"/g, '""')}"`;
        }).join(',')
      )
    ];

    const csvString = csvRows.join('\n');
    const filename = `${title.replace(/\s+/g, '_')}_${new Date().getTime()}.csv`;
    const cacheDir = FileSystem.cacheDirectory;
    const fileUri = `${cacheDir}${filename}`;

    try {
      await FileSystem.writeAsStringAsync(fileUri, csvString, { encoding: FileSystem.EncodingType.UTF8 });
      await Sharing.shareAsync(fileUri, { mimeType: 'text/csv', dialogTitle: `Export ${title}` });
    } catch (e) {
      console.error('CSV Export Error:', e);
      alert('Failed to generate CSV');
    }
  },

  /**
   * Generates a PDF using HTML template and expo-print.
   */
  async downloadPDF(title: string, data: any[]) {
    if (data.length === 0) return alert('No data to export');

    const headers = Object.keys(data[0]);

    const html = `
      <html>
        <head>
          <style>
            body { font-family: 'Helvetica', sans-serif; padding: 20px; }
            h1 { color: #1e3a8a; text-align: center; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { border: 1px solid #ddd; padding: 12px; text-align: left; font-size: 10px; }
            th { background-color: #f3f4f6; color: #374151; font-weight: bold; }
            tr:nth-child(even) { background-color: #f9fafb; }
            .footer { margin-top: 30px; font-size: 8px; color: #9ca3af; text-align: center; }
          </style>
        </head>
        <body>
          <h1>${title}</h1>
          <table>
            <thead>
              <tr>
                ${headers.map(h => `<th>${h.toUpperCase()}</th>`).join('')}
              </tr>
            </thead>
            <tbody>
              ${data.map(row => `
                <tr>
                  ${headers.map(h => `<td>${row[h] ?? ''}</td>`).join('')}
                </tr>
              `).join('')}
            </tbody>
          </table>
          <div class="footer">Generated by SUJATA Maintenance System on ${new Date().toLocaleString()}</div>
        </body>
      </html>
    `;

    try {
      const { uri } = await Print.printToFileAsync({ html });
      const filename = `${title.replace(/\s+/g, '_')}_${new Date().getTime()}.pdf`;
      const cacheDir = FileSystem.cacheDirectory;
      const permanentUri = `${cacheDir}${filename}`;

      await FileSystem.moveAsync({ from: uri, to: permanentUri });
      await Sharing.shareAsync(permanentUri, { mimeType: 'application/pdf', dialogTitle: `Export ${title}` });
    } catch (e) {
      console.error('PDF Export Error:', e);
      alert('Failed to generate PDF');
    }
  },

  /**
   * Fetches equipment data from the DB.
   */
  getEquipmentReport() {
    const db = getDB();
    return db.getAllSync('SELECT equipment_id, name, section, location, manufacturer, model_number, serial_number, status, installation_date FROM Equipment');
  },

  /**
   * Fetches maintenance history from the DB.
   */
  getMaintenanceReport() {
    const db = getDB();
    return db.getAllSync(`
      SELECT 
        e.name as equipment,
        l.maintenance_date,
        l.maintainer_name,
        l.status,
        l.remarks
      FROM Maintenance_Log l
      JOIN Equipment e ON l.equipment_id = e.id
      ORDER BY l.maintenance_date DESC
    `);
  },

  /**
   * Fetches spare parts inventory from the DB.
   */
  getSparesReport() {
    const db = getDB();
    return db.getAllSync(`
      SELECT 
        s.name, 
        s.part_number, 
        s.available_quantity, 
        s.minimum_quantity, 
        s.price,
        s.location,
        s.keeper_name
      FROM Spare_Parts s
    `);
  }
};
